[package]
name = "advent_of_code"
version = "0.8.0"
authors = ["Felix Spöttel <1682504+fspoettel@users.noreply.github.com>"]
edition = "2021"
default-run = "advent_of_code"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.4.2"
itertools = "0.10.5"
lazy_static = "1.4.0"
nom = "7.1.1"
pico-args = "0.5.0"
ranges = "0.3.3"
regex = "1.7.0"
